export const SAVED_ADD_REQUEST = "CART_ADD_REQUEST";
export const SAVED_ADD_SUCCESS = "CART_ADD_SUCCESS";
export const SAVED_ADD_FAIL = "CART_ADD_FAIL";

export const SAVED_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const SAVED_GET_ITEM_REQUEST = "SAVED_GET_ITEM_REQUEST";
export const SAVED_GET_ITEM_SUCCESS = "SAVED_GET_ITEM_SUCCESS";
export const SAVED_GET_ITEM_FAIL = "SAVED_GET_ITEM_FAIL";
